
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self


class MountsUpdateRequest(BaseModel):
    """MountsUpdateRequest
    """  # noqa: E501

    mount_id: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="mountId")
    type: StrictStr | None = None
    host_path: StrictStr | None = Field(default=None, alias="hostPath")
    volume_name: StrictStr | None = Field(default=None, alias="volumeName")
    file_path: StrictStr | None = Field(default=None, alias="filePath")
    content: StrictStr | None = None
    service_type: StrictStr | None = Field(default="application", alias="serviceType")
    mount_path: Annotated[str, Field(min_length=1, strict=True)] | None = Field(default=None, alias="mountPath")
    application_id: StrictStr | None = Field(default=None, alias="applicationId")
    postgres_id: StrictStr | None = Field(default=None, alias="postgresId")
    mariadb_id: StrictStr | None = Field(default=None, alias="mariadbId")
    mongo_id: StrictStr | None = Field(default=None, alias="mongoId")
    mysql_id: StrictStr | None = Field(default=None, alias="mysqlId")
    redis_id: StrictStr | None = Field(default=None, alias="redisId")
    compose_id: StrictStr | None = Field(default=None, alias="composeId")
    __properties: ClassVar[list[str]] = [
        "mountId",
        "type",
        "hostPath",
        "volumeName",
        "filePath",
        "content",
        "serviceType",
        "mountPath",
        "applicationId",
        "postgresId",
        "mariadbId",
        "mongoId",
        "mysqlId",
        "redisId",
        "composeId",
    ]

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["bind", "volume", "file"]):
            raise ValueError("must be one of enum values ('bind', 'volume', 'file')")
        return value

    @field_validator("service_type")
    def service_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["application", "postgres", "mysql", "mariadb", "mongo", "redis", "compose"]):
            raise ValueError(
                "must be one of enum values ('application', 'postgres', 'mysql', 'mariadb', 'mongo', 'redis', 'compose')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of MountsUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if host_path (nullable) is None
        # and model_fields_set contains the field
        if self.host_path is None and "host_path" in self.model_fields_set:
            _dict["hostPath"] = None

        # set to None if volume_name (nullable) is None
        # and model_fields_set contains the field
        if self.volume_name is None and "volume_name" in self.model_fields_set:
            _dict["volumeName"] = None

        # set to None if file_path (nullable) is None
        # and model_fields_set contains the field
        if self.file_path is None and "file_path" in self.model_fields_set:
            _dict["filePath"] = None

        # set to None if content (nullable) is None
        # and model_fields_set contains the field
        if self.content is None and "content" in self.model_fields_set:
            _dict["content"] = None

        # set to None if application_id (nullable) is None
        # and model_fields_set contains the field
        if self.application_id is None and "application_id" in self.model_fields_set:
            _dict["applicationId"] = None

        # set to None if postgres_id (nullable) is None
        # and model_fields_set contains the field
        if self.postgres_id is None and "postgres_id" in self.model_fields_set:
            _dict["postgresId"] = None

        # set to None if mariadb_id (nullable) is None
        # and model_fields_set contains the field
        if self.mariadb_id is None and "mariadb_id" in self.model_fields_set:
            _dict["mariadbId"] = None

        # set to None if mongo_id (nullable) is None
        # and model_fields_set contains the field
        if self.mongo_id is None and "mongo_id" in self.model_fields_set:
            _dict["mongoId"] = None

        # set to None if mysql_id (nullable) is None
        # and model_fields_set contains the field
        if self.mysql_id is None and "mysql_id" in self.model_fields_set:
            _dict["mysqlId"] = None

        # set to None if redis_id (nullable) is None
        # and model_fields_set contains the field
        if self.redis_id is None and "redis_id" in self.model_fields_set:
            _dict["redisId"] = None

        # set to None if compose_id (nullable) is None
        # and model_fields_set contains the field
        if self.compose_id is None and "compose_id" in self.model_fields_set:
            _dict["composeId"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of MountsUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "mountId": obj.get("mountId"),
                "type": obj.get("type"),
                "hostPath": obj.get("hostPath"),
                "volumeName": obj.get("volumeName"),
                "filePath": obj.get("filePath"),
                "content": obj.get("content"),
                "serviceType": obj.get("serviceType") if obj.get("serviceType") is not None else "application",
                "mountPath": obj.get("mountPath"),
                "applicationId": obj.get("applicationId"),
                "postgresId": obj.get("postgresId"),
                "mariadbId": obj.get("mariadbId"),
                "mongoId": obj.get("mongoId"),
                "mysqlId": obj.get("mysqlId"),
                "redisId": obj.get("redisId"),
                "composeId": obj.get("composeId"),
            }
        )
        return _obj
