
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.mounts_create_request import MountsCreateRequest


class TestMountsCreateRequest(unittest.TestCase):
    """MountsCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MountsCreateRequest:
        """Test MountsCreateRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `MountsCreateRequest`
        """
        model = MountsCreateRequest()
        if include_optional:
            return MountsCreateRequest(
                type = 'bind',
                host_path = '',
                volume_name = '',
                content = '',
                mount_path = '0',
                service_type = 'application',
                file_path = '',
                service_id = '0'
            )
        else:
            return MountsCreateRequest(
                type = 'bind',
                mount_path = '0',
                service_id = '0',
        )
        """

    def testMountsCreateRequest(self):
        """Test MountsCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
