
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.api.registry_api import RegistryApi


class TestRegistryApi(unittest.TestCase):
    """RegistryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RegistryApi()

    def tearDown(self) -> None:
        pass

    def test_registry_all(self) -> None:
        """Test case for registry_all"""
        pass

    def test_registry_create(self) -> None:
        """Test case for registry_create"""
        pass

    def test_registry_enable_self_hosted_registry(self) -> None:
        """Test case for registry_enable_self_hosted_registry"""
        pass

    def test_registry_one(self) -> None:
        """Test case for registry_one"""
        pass

    def test_registry_remove(self) -> None:
        """Test case for registry_remove"""
        pass

    def test_registry_test_registry(self) -> None:
        """Test case for registry_test_registry"""
        pass

    def test_registry_update(self) -> None:
        """Test case for registry_update"""
        pass


if __name__ == "__main__":
    unittest.main()
