
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.notification_create_slack_request import NotificationCreateSlackRequest


class TestNotificationCreateSlackRequest(unittest.TestCase):
    """NotificationCreateSlackRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationCreateSlackRequest:
        """Test NotificationCreateSlackRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `NotificationCreateSlackRequest`
        """
        model = NotificationCreateSlackRequest()
        if include_optional:
            return NotificationCreateSlackRequest(
                app_build_error = True,
                database_backup = True,
                dokploy_restart = True,
                name = '',
                app_deploy = True,
                docker_cleanup = True,
                webhook_url = '0',
                channel = ''
            )
        else:
            return NotificationCreateSlackRequest(
                app_build_error = True,
                database_backup = True,
                dokploy_restart = True,
                name = '',
                app_deploy = True,
                docker_cleanup = True,
                webhook_url = '0',
                channel = '',
        )
        """

    def testNotificationCreateSlackRequest(self):
        """Test NotificationCreateSlackRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
