
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.compose_update_request import ComposeUpdateRequest


class TestComposeUpdateRequest(unittest.TestCase):
    """ComposeUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComposeUpdateRequest:
        """Test ComposeUpdateRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `ComposeUpdateRequest`
        """
        model = ComposeUpdateRequest()
        if include_optional:
            return ComposeUpdateRequest(
                compose_id = '',
                name = '0',
                app_name = '',
                description = '',
                env = '',
                compose_file = '',
                refresh_token = '',
                source_type = 'git',
                compose_type = 'docker-compose',
                repository = '',
                owner = '',
                branch = '',
                auto_deploy = True,
                custom_git_url = '',
                custom_git_branch = '',
                custom_git_ssh_key_id = '',
                command = '',
                compose_path = '0',
                compose_status = 'idle',
                project_id = '',
                created_at = ''
            )
        else:
            return ComposeUpdateRequest(
                compose_id = '',
        )
        """

    def testComposeUpdateRequest(self):
        """Test ComposeUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
