
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.api.application_api import ApplicationApi


class TestApplicationApi(unittest.TestCase):
    """ApplicationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApplicationApi()

    def tearDown(self) -> None:
        pass

    def test_application_clean_queues(self) -> None:
        """Test case for application_clean_queues"""
        pass

    def test_application_create(self) -> None:
        """Test case for application_create"""
        pass

    def test_application_delete(self) -> None:
        """Test case for application_delete"""
        pass

    def test_application_deploy(self) -> None:
        """Test case for application_deploy"""
        pass

    def test_application_mark_running(self) -> None:
        """Test case for application_mark_running"""
        pass

    def test_application_one(self) -> None:
        """Test case for application_one"""
        pass

    def test_application_read_app_monitoring(self) -> None:
        """Test case for application_read_app_monitoring"""
        pass

    def test_application_read_traefik_config(self) -> None:
        """Test case for application_read_traefik_config"""
        pass

    def test_application_redeploy(self) -> None:
        """Test case for application_redeploy"""
        pass

    def test_application_refresh_token(self) -> None:
        """Test case for application_refresh_token"""
        pass

    def test_application_reload(self) -> None:
        """Test case for application_reload"""
        pass

    def test_application_save_build_type(self) -> None:
        """Test case for application_save_build_type"""
        pass

    def test_application_save_docker_provider(self) -> None:
        """Test case for application_save_docker_provider"""
        pass

    def test_application_save_environment(self) -> None:
        """Test case for application_save_environment"""
        pass

    def test_application_save_git_prodiver(self) -> None:
        """Test case for application_save_git_prodiver"""
        pass

    def test_application_save_github_provider(self) -> None:
        """Test case for application_save_github_provider"""
        pass

    def test_application_start(self) -> None:
        """Test case for application_start"""
        pass

    def test_application_stop(self) -> None:
        """Test case for application_stop"""
        pass

    def test_application_update(self) -> None:
        """Test case for application_update"""
        pass

    def test_application_update_traefik_config(self) -> None:
        """Test case for application_update_traefik_config"""
        pass


if __name__ == "__main__":
    unittest.main()
