
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.domain_update_request import DomainUpdateRequest


class TestDomainUpdateRequest(unittest.TestCase):
    """DomainUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DomainUpdateRequest:
        """Test DomainUpdateRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `DomainUpdateRequest`
        """
        model = DomainUpdateRequest()
        if include_optional:
            return DomainUpdateRequest(
                host = 'gA9LCSLv1C1ylmgd0.Y2TA5TkIRHR.TIxMOOYsCSLvdNTRddzXYdswQltRTtwKQzBuNJxBelKTmfI',
                path = '0',
                port = 1,
                https = True,
                certificate_type = 'letsencrypt',
                domain_id = ''
            )
        else:
            return DomainUpdateRequest(
                host = 'gA9LCSLv1C1ylmgd0.Y2TA5TkIRHR.TIxMOOYsCSLvdNTRddzXYdswQltRTtwKQzBuNJxBelKTmfI',
                domain_id = '',
        )
        """

    def testDomainUpdateRequest(self):
        """Test DomainUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
