
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.api.ssh_key_api import SshKeyApi


class TestSshKeyApi(unittest.TestCase):
    """SshKeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SshKeyApi()

    def tearDown(self) -> None:
        pass

    def test_ssh_key_all(self) -> None:
        """Test case for ssh_key_all"""
        pass

    def test_ssh_key_create(self) -> None:
        """Test case for ssh_key_create"""
        pass

    def test_ssh_key_generate(self) -> None:
        """Test case for ssh_key_generate"""
        pass

    def test_ssh_key_one(self) -> None:
        """Test case for ssh_key_one"""
        pass

    def test_ssh_key_remove(self) -> None:
        """Test case for ssh_key_remove"""
        pass

    def test_ssh_key_update(self) -> None:
        """Test case for ssh_key_update"""
        pass


if __name__ == "__main__":
    unittest.main()
