
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_user_all(self) -> None:
        """Test case for user_all"""
        pass

    def test_user_by_auth_id(self) -> None:
        """Test case for user_by_auth_id"""
        pass

    def test_user_by_user_id(self) -> None:
        """Test case for user_by_user_id"""
        pass


if __name__ == "__main__":
    unittest.main()
