
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.auth_verify_login2_fa_request import AuthVerifyLogin2FARequest


class TestAuthVerifyLogin2FARequest(unittest.TestCase):
    """AuthVerifyLogin2FARequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthVerifyLogin2FARequest:
        """Test AuthVerifyLogin2FARequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `AuthVerifyLogin2FARequest`
        """
        model = AuthVerifyLogin2FARequest()
        if include_optional:
            return AuthVerifyLogin2FARequest(
                pin = '012345',
                id = ''
            )
        else:
            return AuthVerifyLogin2FARequest(
                pin = '012345',
                id = '',
        )
        """

    def testAuthVerifyLogin2FARequest(self):
        """Test AuthVerifyLogin2FARequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
