
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.application_update_request_restart_policy_swarm import (
    ApplicationUpdateRequestRestartPolicySwarm,
)


class TestApplicationUpdateRequestRestartPolicySwarm(unittest.TestCase):
    """ApplicationUpdateRequestRestartPolicySwarm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicationUpdateRequestRestartPolicySwarm:
        """Test ApplicationUpdateRequestRestartPolicySwarm
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `ApplicationUpdateRequestRestartPolicySwarm`
        """
        model = ApplicationUpdateRequestRestartPolicySwarm()
        if include_optional:
            return ApplicationUpdateRequestRestartPolicySwarm(
                condition = '',
                delay = 1.337,
                max_attempts = 1.337,
                window = 1.337
            )
        else:
            return ApplicationUpdateRequestRestartPolicySwarm(
        )
        """

    def testApplicationUpdateRequestRestartPolicySwarm(self):
        """Test ApplicationUpdateRequestRestartPolicySwarm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
