
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.ssh_key_remove_request import SshKeyRemoveRequest


class TestSshKeyRemoveRequest(unittest.TestCase):
    """SshKeyRemoveRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SshKeyRemoveRequest:
        """Test SshKeyRemoveRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `SshKeyRemoveRequest`
        """
        model = SshKeyRemoveRequest()
        if include_optional:
            return SshKeyRemoveRequest(
                ssh_key_id = ''
            )
        else:
            return SshKeyRemoveRequest(
                ssh_key_id = '',
        )
        """

    def testSshKeyRemoveRequest(self):
        """Test SshKeyRemoveRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
