
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.api.domain_api import DomainApi


class TestDomainApi(unittest.TestCase):
    """DomainApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DomainApi()

    def tearDown(self) -> None:
        pass

    def test_domain_by_application_id(self) -> None:
        """Test case for domain_by_application_id"""
        pass

    def test_domain_create(self) -> None:
        """Test case for domain_create"""
        pass

    def test_domain_delete(self) -> None:
        """Test case for domain_delete"""
        pass

    def test_domain_generate_domain(self) -> None:
        """Test case for domain_generate_domain"""
        pass

    def test_domain_generate_wildcard(self) -> None:
        """Test case for domain_generate_wildcard"""
        pass

    def test_domain_one(self) -> None:
        """Test case for domain_one"""
        pass

    def test_domain_update(self) -> None:
        """Test case for domain_update"""
        pass


if __name__ == "__main__":
    unittest.main()
