
"""Dokploy API

Endpoints for dokploy

The version of the OpenAPI document: v0.6.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openapi_client.models.redis_update_request import RedisUpdateRequest


class TestRedisUpdateRequest(unittest.TestCase):
    """RedisUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RedisUpdateRequest:
        """Test RedisUpdateRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included
        """
        # uncomment below to create an instance of `RedisUpdateRequest`
        """
        model = RedisUpdateRequest()
        if include_optional:
            return RedisUpdateRequest(
                redis_id = '0',
                name = '0',
                app_name = '0',
                description = '',
                database_password = '',
                docker_image = 'redis:8',
                command = '',
                env = '',
                memory_reservation = 1.337,
                memory_limit = 1.337,
                cpu_reservation = 1.337,
                cpu_limit = 1.337,
                external_port = 1.337,
                created_at = '',
                application_status = 'idle',
                project_id = ''
            )
        else:
            return RedisUpdateRequest(
                redis_id = '0',
        )
        """

    def testRedisUpdateRequest(self):
        """Test RedisUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
